# Cleaning the Station Files

### Local Imports

In [16]:
from cs1.stations import *
from cs1.tools import *

### Station Files

In [2]:
STATION_FILES

[PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2015.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Trips_2016_Q1Q2/Divvy_Stations_2016_Q1Q2.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q1Q2.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q3Q4.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2013/Divvy_Stations_2013.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q4.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q3.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2014_Q3Q4/Divvy_Stations_2014-Q3Q4.csv')]

The column names in the station files are inconsistent, but not as badly as those of the trip files.

In [4]:
set([str(L) for L in station_columns()])

{"['id', 'name', 'city', 'latitude', 'longitude', 'dpcapacity', 'online_date', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'dateCreated', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'landmark', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'landmark', 'online date', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'online_date', '', '', '', '', '', '', '']"}

In [5]:
from cs1.tools import *
from cs1.stations import *

In [6]:
df = combine_station_files()

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2015.csv
   ID                      Name   Latitude  Longitude  DP Capacity  Landmark
0   2  Michigan Ave & Balbo Ave  41.872293 -87.624091           35       541
1   3            Shedd Aquarium  41.867226 -87.615355           31       544
2   4            Burnham Harbor  41.856268 -87.613348           23       545
3   5    State St & Harrison St  41.874053 -87.627716           23        30
4   6            Dusable Harbor  41.885042 -87.612795           31       548
len(df_sum)=474

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Trips_2016_Q1Q2/Divvy_Stations_2016_Q1Q2.csv
    ID                        Name   Latitude  Longitude  DP Capacity  \
0  456         2112 W Peterson Ave  41.991178 -87.683593           15
1  101               63rd St Beach  41.781016 -87.576120           23
2  109           900 W Harrison St  41.874675 -87.650019           19
3   21  Aberdeen St & Jackson Blvd  41.877726 -87.654787           15
4   80     Aberdeen St & Monroe St  41.880456 -87.653929           19

  Online Date
0   5/12/2015
1   4/20/2015
2    8/6/2013
3   6/21/2013
4   6/26/2013
len(df_sum)=1009

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q1Q2.csv
    ID                               Name     City   Latitude  Longitude  \
0  456                2112 W Peterson Ave  Chicago  41.991178 -87.683593
1  101                      63rd St Beach  Chicago  41.781016 -87.576120
2  109                  900 W Harrison St  Chicago  41.874675 -87.650019
3   21         Aberdeen St & Jackson Blvd  Chicago  41.877726 -87.654787
4   80  Aberdeen St & Madison (Monroe) St  Chicago  41.881567 -87.655056

   DP Capacity         Online Date
0           15  2/10/2015 14:04:42
1           23  7/16/2013 01:27:50
2           19  7/18/2013 16:45:02
3           15  6/22/2013 19:07:12
4           19  6/26/2013 19:00:18
len(df_sum)=1591

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q3Q4.csv
Bad lookup value: Unnamed: 7
File: Divvy_Stations_2017_Q3Q4.csv
Dropping column...
   ID                    Name     City   Latitude  Longitude  DP Capacity  \
0   2     Buckingham Fountain  Chicago  41.876393 -87.620328           27
1   3          Shedd Aquarium  Chicago  41.867226 -87.615355           55
2   4          Burnham Harbor  Chicago  41.856268 -87.613348           23
3   5  State St & Harrison St  Chicago  41.874053 -87.627716           23
4   6          Dusable Harbor  Chicago  41.885041 -87.612794           39

       Online Date  None
0  6/10/2013 10:43   NaN
1  6/10/2013 10:44   NaN
2  6/10/2013 10:46   NaN
3  6/10/2013 10:46   NaN
4  6/10/2013 11:18   NaN
len(df_sum)=2176

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2013/Divvy_Stations_2013.csv
   ID                        Name   Latitude  Longitude  DP Capacity  \
0   5      State St & Harrison St  41.873958 -87.627739           19
1  13  Wilton Ave & Diversey Pkwy  41.932500 -87.652681           19
2  14         Morgan St & 18th St  41.858086 -87.651073           15
3  15        Racine Ave & 18th St  41.858181 -87.656487           15
4  16         Wood St & North Ave  41.910329 -87.672516           15

   Landmark Online Date
0        30   6/28/2013
1        66   6/28/2013
2       163   6/28/2013
3       164   6/28/2013
4       223   8/12/2013
len(df_sum)=2476

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q4.csv
    ID                        Name   Latitude  Longitude  DP Capacity  \
0  456         2112 W Peterson Ave  41.991178 -87.683593           15
1  101               63rd St Beach  41.781016 -87.576120           23
2  109           900 W Harrison St  41.874675 -87.650019           19
3   21  Aberdeen St & Jackson Blvd  41.877726 -87.654787           15
4   80     Aberdeen St & Monroe St  41.880420 -87.655599           19

  Online Date
0   5/12/2015
1   4/20/2015
2    8/6/2013
3   6/21/2013
4   6/26/2013
len(df_sum)=3057

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q3.csv
    ID                        Name   Latitude  Longitude  DP Capacity  \
0  456         2112 W Peterson Ave  41.991178 -87.683593           15
1  101               63rd St Beach  41.781016 -87.576120           23
2  109           900 W Harrison St  41.874675 -87.650019           19
3   21  Aberdeen St & Jackson Blvd  41.877726 -87.654787           15
4   80     Aberdeen St & Monroe St  41.880420 -87.655599           19

  Online Date
0   5/12/2015
1   4/20/2015
2    8/6/2013
3   6/21/2013
4   6/26/2013
len(df_sum)=3638

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2014_Q3Q4/Divvy_Stations_2014-Q3Q4.csv
   ID                        Name   Latitude  Longitude  DP Capacity  \
0   5      State St & Harrison St  41.873958 -87.627739           19
1  13  Wilton Ave & Diversey Pkwy  41.932500 -87.652681           19
2  14         Morgan St & 18th St  41.858086 -87.651073           15
3  15        Racine Ave & 19th St  41.856453 -87.656471           15
4  16         Wood St & North Ave  41.910329 -87.672516           15

       Online Date
0  6/10/2013 10:46
1  6/22/2013 18:29
2  6/22/2013 18:33
3  6/22/2013 18:35
4  6/22/2013 18:55
len(df_sum)=3938

      ID                         Name   Latitude  Longitude  DP Capacity  \
0      2     Michigan Ave & Balbo Ave  41.872293 -87.624091           35
1      3               Shedd Aquarium  41.867226 -87.615355           31
2      4               Burnham Harbor  41.856268 -87.613348           23
3      5       State St & Harrison St  41.874053 -87.627716           23
4      6               Dusable Harbor  41.885042 -87.612795           31
..   ...                          ...        ...        ...          ...
295  347       Ashland Ave & Grace St  41.950687 -87.668700           15
296  348     California Ave & 21st St  41.854016 -87.695445           15
297  349  Halsted St & Wrightwood Ave  41.929143 -87.649077           15
298  350    Ashland Ave & Chicago Ave  41.895966 -87.667747           15
299  351  Cottage Grove Ave & 51st St  41.803038 -87.606615           15

     Landmark       Online Date City  None
0       541.0               NaN  NaN   NaN
1       544.0               NaN  NaN   NaN
2       545.0               NaN  NaN   NaN
3        30.0               NaN  NaN   NaN
4       548.0               NaN  NaN   NaN
..        ...               ...  ...   ...
295       NaN   10/4/2013 16:06  NaN   NaN
296       NaN   10/9/2013 16:13  NaN   NaN
297       NaN  10/10/2013 12:40  NaN   NaN
298       NaN  10/10/2013 14:22  NaN   NaN
299       NaN  10/10/2013 16:56  NaN   NaN

[3938 rows x 9 columns]

In [7]:
df.columns

Index(['ID', 'Name', 'Latitude', 'Longitude', 'DP Capacity', 'Landmark',
       'Online Date', 'City'],
      dtype='object')

In [8]:
len(df['ID'].unique())

586

In [9]:
backup_df = df.copy()

In [6]:
# df = backup_df

In [10]:
df

,ID,Name,Latitude,Longitude,DP Capacity,Landmark,Online Date,City
0,2,Michigan Ave & Balbo Ave,41.872293,-87.624091,35,541.0,NaN,NaN
357,2,Michigan Ave & Balbo Ave,41.872638,-87.623979,35,NaN,5/8/2015,NaN
52,2,Buckingham Fountain,41.881060,-87.619486,27,NaN,6/10/2013 10:43:46,Chicago
357,2,Michigan Ave & Balbo Ave,41.872638,-87.623979,35,NaN,5/8/2015,NaN
0,2,Buckingham Fountain,41.876393,-87.620328,27,NaN,6/10/2013 10:43,Chicago
...,...,...,...,...,...,...,...,...
581,623,Michigan Ave & 8th St,41.872773,-87.623981,31,NaN,6/13/2017 15:23,Chicago
339,623,Michigan Ave & 8th St,41.872773,-87.623981,23,NaN,6/13/2017 15:23:53,Chicago
582,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,NaN,7/26/2017 21:25,Chicago
583,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,NaN,8/11/2017 16:53,Evanston
584,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,NaN,12/21/2017 22:06,Chicago

In [11]:
df["Name"] = df["Name"].replace(r' \(\*\)', '')

In [12]:
type(df["Online Date"].dtype)

numpy.dtype[object_]

In [13]:
new_df = condense_stations(df)

Running
len(IDs)=586

i=2
     ID                      Name   Latitude  Longitude  DP Capacity  \
52    2       Buckingham Fountain  41.881060 -87.619486           27
0     2       Buckingham Fountain  41.876393 -87.620328           27
357   2  Michigan Ave & Balbo Ave  41.872638 -87.623979           35
357   2  Michigan Ave & Balbo Ave  41.872638 -87.623979           35
47    2       Buckingham Fountain  41.872667 -87.623971           35
0     2  Michigan Ave & Balbo Ave  41.872293 -87.624091           35

     Landmark         Online Date     City
52        NaN  6/10/2013 10:43:46  Chicago
0         NaN     6/10/2013 10:43  Chicago
357       NaN            5/8/2015      NaN
357       NaN            5/8/2015      NaN
47        NaN            5/8/2015      NaN
0       541.0                 NaN      NaN

Online Dates: {datetime.date(2015, 5, 8), datetime.date(2013, 6, 10)}
Most recent date: 2015-05-08
names=['Michigan Ave & Balbo Ave', 'Michigan Ave & Balbo Ave', 'Buckingham Fountain']
unique_names=['Buckingham Fountain', 'Michigan Ave & Balbo Ave']
{'Name': ['Buckingham Fountain', 'Michigan Ave & Balbo Ave'], 'Popularity': [3, 3]}
                       Name  Popularity
0       Buckingham Fountain           3
1  Michigan Ave & Balbo Ave           3
name='Buckingham Fountain'
C=52    Chicago
0     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.87461483333333
longitude=-87.62263899999999

i=3
     ID            Name   Latitude  Longitude  DP Capacity  Landmark  \
440   3  Shedd Aquarium  41.867226 -87.615355           31       NaN
1     3  Shedd Aquarium  41.867226 -87.615355           55       NaN
409   3  Shedd Aquarium  41.867226 -87.615355           31       NaN
456   3  Shedd Aquarium  41.867226 -87.615355           31       NaN
456   3  Shedd Aquarium  41.867226 -87.615355           31       NaN
1     3  Shedd Aquarium  41.867226 -87.615355           31     544.0

            Online Date     City
440  6/10/2013 10:44:48  Chicago
1       6/10/2013 10:44  Chicago
409           4/24/2015      NaN
456           4/24/2015      NaN
456           4/24/2015      NaN
1                   NaN      NaN

Online Dates: {datetime.date(2015, 4, 24), datetime.date(2013, 6, 10)}
Most recent date: 2015-04-24
names=['Shedd Aquarium', 'Shedd Aquarium', 'Shedd Aquarium']
unique_names=['Shedd Aquarium']
{'Name': ['Shedd Aquarium'], 'Popularity': [6]}
             Name  Popularity
0  Shedd Aquarium           6
name='Shedd Aquarium'
C=440    Chicago
1      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.867225966136665
longitude=-87.61535532503332

i=4
    ID            Name   Latitude  Longitude  DP Capacity  Landmark  \
54   4  Burnham Harbor  41.856268 -87.613348           23       NaN
2    4  Burnham Harbor  41.856268 -87.613348           23       NaN
53   4  Burnham Harbor  41.856268 -87.613348           23       NaN
49   4  Burnham Harbor  41.856268 -87.613348           23       NaN
53   4  Burnham Harbor  41.856268 -87.613348           23       NaN
2    4  Burnham Harbor  41.856268 -87.613348           23     545.0

           Online Date     City
54  6/10/2013 10:46:02  Chicago
2      6/10/2013 10:46  Chicago
53           5/16/2015      NaN
49           5/16/2015      NaN
53           5/16/2015      NaN
2                  NaN      NaN

Online Dates: {datetime.date(2015, 5, 16), datetime.date(2013, 6, 10)}
Most recent date: 2015-05-16
names=['Burnham Harbor', 'Burnham Harbor', 'Burnham Harbor']
unique_names=['Burnham Harbor']
{'Name': ['Burnham Harbor'], 'Popularity': [6]}
             Name  Popularity
0  Burnham Harbor           6
name='Burnham Harbor'
C=54    Chicago
2     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.856268
longitude=-87.61334799999999

i=5
     ID                    Name   Latitude  Longitude  DP Capacity  Landmark  \
0     5  State St & Harrison St  41.873958 -87.627739           19      30.0
497   5  State St & Harrison St  41.874053 -87.627716           23       NaN
497   5  State St & Harrison St  41.874053 -87.627716           23       NaN
447   5  State St & Harrison St  41.874053 -87.627716           23       NaN
480   5  State St & Harrison St  41.874053 -87.627716           23       NaN
3     5  State St & Harrison St  41.874053 -87.627716           23       NaN
0     5  State St & Harrison St  41.873958 -87.627739           19       NaN
3     5  State St & Harrison St  41.874053 -87.627716           23      30.0

            Online Date     City
0             6/28/2013      NaN
497           6/18/2013      NaN
497           6/18/2013      NaN
447           6/18/2013      NaN
480  6/10/2013 10:46:54  Chicago
3       6/10/2013 10:46  Chicago
0       6/10/2013 10:46      NaN
3                   NaN      NaN

Online Dates: {datetime.date(2013, 6, 18), datetime.date(2013, 6, 28), datetime.date(2013, 6, 10)}
Most recent date: 2013-06-28
names=['State St & Harrison St']
unique_names=['State St & Harrison St']
{'Name': ['State St & Harrison St'], 'Popularity': [8]}
                     Name  Popularity
0  State St & Harrison St           8
name='State St & Harrison St'
C=480    Chicago
3      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.874029265000004
longitude=-87.62772187249999

i=6
     ID            Name   Latitude  Longitude  DP Capacity  Landmark  \
182   6  Dusable Harbor  41.885042 -87.612795           39       NaN
4     6  Dusable Harbor  41.885041 -87.612794           39       NaN
188   6  Dusable Harbor  41.885042 -87.612795           31       NaN
188   6  Dusable Harbor  41.885042 -87.612795           31       NaN
171   6  DuSable Harbor  41.885042 -87.612795           31       NaN
4     6  Dusable Harbor  41.885042 -87.612795           31     548.0

            Online Date     City
182  6/10/2013 11:18:52  Chicago
4       6/10/2013 11:18  Chicago
188           4/24/2015      NaN
188           4/24/2015      NaN
171           4/24/2015      NaN
4                   NaN      NaN

Online Dates: {datetime.date(2015, 4, 24), datetime.date(2013, 6, 10)}
Most recent date: 2015-04-24
names=['Dusable Harbor', 'Dusable Harbor', 'DuSable Harbor']
unique_names=['DuSable Harbor', 'Dusable Harbor']
{'Name': ['DuSable Harbor', 'Dusable Harbor'], 'Popularity': [1, 5]}
             Name  Popularity
1  Dusable Harbor           5
0  DuSable Harbor           1
name='DuSable Harbor'
C=182    Chicago
4      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.88504182705333
longitude=-87.61279452656667

i=7
     ID                         Name   Latitude  Longitude  DP Capacity  \
201   7  Field Blvd & South Water St  41.886349 -87.617517           19
5     7  Field Blvd & South Water St  41.886349 -87.617517           19
187   7  Field Blvd & South Water St  41.886349 -87.617517           19
210   7  Field Blvd & South Water St  41.886349 -87.617517           19
210   7  Field Blvd & South Water St  41.886349 -87.617517           19
5     7  Field Blvd & South Water St  41.886349 -87.617517           19

     Landmark         Online Date     City
201       NaN  6/19/2013 10:00:21  Chicago
5         NaN     6/19/2013 10:00  Chicago
187       NaN           4/18/2015      NaN
210       NaN           4/18/2015      NaN
210       NaN           4/18/2015      NaN
5       534.0                 NaN      NaN

Online Dates: {datetime.date(2013, 6, 19), datetime.date(2015, 4, 18)}
Most recent date: 2015-04-18
names=['Field Blvd & South Water St', 'Field Blvd & South Water St', 'Field Blvd & South Water St']
unique_names=['Field Blvd & South Water St']
{'Name': ['Field Blvd & South Water St'], 'Popularity': [6]}
                          Name  Popularity
0  Field Blvd & South Water St           6
name='Field Blvd & South Water St'
C=201    Chicago
5      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.88634905044833
longitude=-87.61751662451667

i=9
     ID                     Name   Latitude  Longitude  DP Capacity  Landmark  \
6     9  Leavitt St & Archer Ave  41.828792 -87.680604           19       NaN
306   9  Leavitt St & Archer Ave  41.828792 -87.680604           19       NaN
287   9  Leavitt St & Archer Ave  41.828792 -87.680604           19       NaN
319   9  Leavitt St & Archer Ave  41.828792 -87.680604           19       NaN
319   9  Leavitt St & Archer Ave  41.828792 -87.680604           19       NaN
6     9  Leavitt St & Archer Ave  41.828792 -87.680604           19     695.0

            Online Date     City
6        6/21/2013 9:33  Chicago
306  6/21/2013 09:33:32  Chicago
287           4/14/2015      NaN
319           4/14/2015      NaN
319           4/14/2015      NaN
6                   NaN      NaN

Online Dates: {datetime.date(2015, 4, 14), datetime.date(2013, 6, 21)}
Most recent date: 2015-04-14
names=['Leavitt St & Archer Ave', 'Leavitt St & Archer Ave', 'Leavitt St & Archer Ave']
unique_names=['Leavitt St & Archer Ave']
{'Name': ['Leavitt St & Archer Ave'], 'Popularity': [6]}
                      Name  Popularity
0  Leavitt St & Archer Ave           6
name='Leavitt St & Archer Ave'
C=6      Chicago
306    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.82879201665667
longitude=-87.68060438323333

i=11
     ID                    Name   Latitude  Longitude  DP Capacity  Landmark  \
7    11  Jeffery Blvd & 71st St  41.766638  -87.57645           11       NaN
252  11  Jeffery Blvd & 71st St  41.766638  -87.57645           11       NaN
265  11  Jeffery Blvd & 71st St  41.766638  -87.57645           11       NaN
265  11  Jeffery Blvd & 71st St  41.766638  -87.57645           11       NaN
235  11  Jeffery Blvd & 71st St  41.766638  -87.57645           11       NaN
7    11  Jeffery Blvd & 71st St  41.766638  -87.57645           11     496.0

            Online Date     City
7        6/21/2013 9:39  Chicago
252  6/21/2013 09:39:15  Chicago
265           4/22/2015      NaN
265           4/22/2015      NaN
235           4/22/2015      NaN
7                   NaN      NaN

Online Dates: {datetime.date(2015, 4, 22), datetime.date(2013, 6, 21)}
Most recent date: 2015-04-22
names=['Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St']
unique_names=['Jeffery Blvd & 71st St']
{'Name': ['Jeffery Blvd & 71st St'], 'Popularity': [6]}
                     Name  Popularity
0  Jeffery Blvd & 71st St           6
name='Jeffery Blvd & 71st St'
C=7      Chicago
252    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.76663819949166
longitude=-87.57645009235

i=12
     ID                      Name   Latitude  Longitude  DP Capacity  \
460  12  South Shore Dr & 71st St  41.766409 -87.565688           15
8    12  South Shore Dr & 71st St  41.766409 -87.565688           15
477  12  South Shore Dr & 71st St  41.766409 -87.565688           15
477  12  South Shore Dr & 71st St  41.766409 -87.565688           15
428  12  South Shore Dr & 71st St  41.766409 -87.565688           15
8    12  South Shore Dr & 71st St  41.766409 -87.565688           15

     Landmark         Online Date     City
460       NaN  6/21/2013 10:00:22  Chicago
8         NaN     6/21/2013 10:00  Chicago
477       NaN           4/22/2015      NaN
477       NaN           4/22/2015      NaN
428       NaN           4/22/2015      NaN
8       497.0                 NaN      NaN

Online Dates: {datetime.date(2015, 4, 22), datetime.date(2013, 6, 21)}
Most recent date: 2015-04-22
names=['South Shore Dr & 71st St', 'South Shore Dr & 71st St', 'South Shore Dr & 71st St']
unique_names=['South Shore Dr & 71st St']
{'Name': ['South Shore Dr & 71st St'], 'Popularity': [6]}
                       Name  Popularity
0  South Shore Dr & 71st St           6
name='South Shore Dr & 71st St'
C=460    Chicago
8      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.76640938278334
longitude=-87.56568764198335

i=13
     ID                        Name   Latitude  Longitude  DP Capacity  \
1    13  Wilton Ave & Diversey Pkwy  41.932500 -87.652681           19
546  13  Wilton Ave & Diversey Pkwy  41.932418 -87.652705           27
1    13  Wilton Ave & Diversey Pkwy  41.932500 -87.652681           19
9    13  Wilton Ave & Diversey Pkwy  41.932418 -87.652705           27
567  13  Wilton Ave & Diversey Pkwy  41.932418 -87.652705           27
508  13  Wilton Ave & Diversey Pkwy  41.932418 -87.652705           27
567  13  Wilton Ave & Diversey Pkwy  41.932418 -87.652705           27
9    13  Wilton Ave & Diversey Pkwy  41.932500 -87.652681           19

     Landmark         Online Date     City
1        66.0           6/28/2013      NaN
546       NaN  6/22/2013 18:29:48  Chicago
1         NaN     6/22/2013 18:29      NaN
9         NaN     6/22/2013 18:29  Chicago
567       NaN           6/20/2013      NaN
508       NaN           6/20/2013      NaN
567       NaN           6/20/2013      NaN
9        66.0                 NaN      NaN

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 6, 20), datetime.date(2013, 6, 28)}
Most recent date: 2013-06-28
names=['Wilton Ave & Diversey Pkwy']
unique_names=['Wilton Ave & Diversey Pkwy']
{'Name': ['Wilton Ave & Diversey Pkwy'], 'Popularity': [8]}
                         Name  Popularity
0  Wilton Ave & Diversey Pkwy           8
name='Wilton Ave & Diversey Pkwy'
C=546    Chicago
9      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.932448779999994
longitude=-87.65269593249998

i=14
     ID                 Name   Latitude  Longitude  DP Capacity  Landmark  \
2    14  Morgan St & 18th St  41.858086 -87.651073           15     163.0
364  14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
10   14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
2    14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
381  14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
343  14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
381  14  Morgan St & 18th St  41.858086 -87.651073           15       NaN
10   14  Morgan St & 18th St  41.858086 -87.651073           15     163.0

            Online Date     City
2             6/28/2013      NaN
364  6/22/2013 18:33:34  Chicago
10      6/22/2013 18:33  Chicago
2       6/22/2013 18:33      NaN
381           6/20/2013      NaN
343           6/20/2013      NaN
381           6/20/2013      NaN
10                  NaN      NaN

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 6, 20), datetime.date(2013, 6, 28)}
Most recent date: 2013-06-28
names=['Morgan St & 18th St']
unique_names=['Morgan St & 18th St']
{'Name': ['Morgan St & 18th St'], 'Popularity': [8]}
                  Name  Popularity
0  Morgan St & 18th St           8
name='Morgan St & 18th St'
C=364    Chicago
10     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.85808600000001
longitude=-87.651073

i=15
     ID                  Name   Latitude  Longitude  DP Capacity  Landmark  \
3    15  Racine Ave & 18th St  41.858181 -87.656487           15     164.0
404  15  Racine Ave & 18th St  41.858166 -87.656495           15       NaN
3    15  Racine Ave & 19th St  41.856453 -87.656471           15       NaN
11   15  Racine Ave & 18th St  41.858166 -87.656495           15       NaN
422  15  Racine Ave & 18th St  41.858166 -87.656495           15       NaN
377  15  Racine Ave & 18th St  41.858166 -87.656495           15       NaN
422  15  Racine Ave & 18th St  41.858166 -87.656495           15       NaN
11   15  Racine Ave & 18th St  41.858166 -87.656495           15     164.0

            Online Date     City
3             6/28/2013      NaN
404  6/22/2013 18:35:45  Chicago
3       6/22/2013 18:35      NaN
11      6/22/2013 18:35  Chicago
422           6/20/2013      NaN
377           6/20/2013      NaN
422           6/20/2013      NaN
11                  NaN      NaN

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 6, 20), datetime.date(2013, 6, 28)}
Most recent date: 2013-06-28
names=['Racine Ave & 18th St']
unique_names=['Racine Ave & 18th St']
{'Name': ['Racine Ave & 18th St'], 'Popularity': [7]}
                   Name  Popularity
0  Racine Ave & 18th St           7
name='Racine Ave & 18th St'
C=404    Chicago
11     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.85795370124999
longitude=-87.65649095625

i=16
     ID                     Name   Latitude  Longitude  DP Capacity  Landmark  \
4    16      Wood St & North Ave  41.910329 -87.672516           15     223.0
402  16  Paulina Ave & North Ave  41.910337 -87.670072           15       NaN
360  16  Paulina Ave & North Ave  41.910337 -87.670072           11       NaN
402  16  Paulina Ave & North Ave  41.910337 -87.670072           15       NaN
384  16  Paulina Ave & North Ave  41.910337 -87.670072           15       NaN
4    16      Wood St & North Ave  41.910329 -87.672516           15       NaN
12   16  Paulina Ave & North Ave  41.910337 -87.670072           15       NaN
12   16      Wood St & North Ave  41.910329 -87.672516           11     223.0

            Online Date     City
4             8/12/2013      NaN
402           8/12/2013      NaN
360           8/12/2013      NaN
402           8/12/2013      NaN
384  6/22/2013 18:55:29  Chicago
4       6/22/2013 18:55      NaN
12      6/22/2013 18:55  Chicago
12                  NaN      NaN

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 8, 12)}
Most recent date: 2013-08-12
names=['Wood St & North Ave', 'Paulina Ave & North Ave', 'Paulina Ave & North Ave', 'Paulina Ave & North Ave']
unique_names=['Paulina Ave & North Ave', 'Wood St & North Ave']
{'Name': ['Paulina Ave & North Ave', 'Wood St & North Ave'], 'Popularity': [5, 3]}
                      Name  Popularity
0  Paulina Ave & North Ave           5
1      Wood St & North Ave           3
name='Paulina Ave & North Ave'
C=384    Chicago
12     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.910334
longitude=-87.67098849999999

i=17
     ID                     Name   Latitude  Longitude  DP Capacity  Landmark  \
5    17    Wood St & Division St  41.903320 -87.672730           15     246.0
551  17    Wood St & Division St  41.903320 -87.672730           15       NaN
5    17    Wood St & Division St  41.903320 -87.672730           15       NaN
13   17  Honore St & Division St  41.903119 -87.673935           23       NaN
573  17    Wood St & Division St  41.903320 -87.672730           15       NaN
512  17    Wood St & Division St  41.903320 -87.672730           15       NaN
573  17    Wood St & Division St  41.903320 -87.672730           15       NaN
13   17    Wood St & Division St  41.903320 -87.672730           15     246.0

            Online Date     City
5             6/28/2013      NaN
551  6/22/2013 18:58:29  Chicago
5       6/22/2013 18:58      NaN
13      6/22/2013 18:58  Chicago
573           6/20/2013      NaN
512           6/20/2013      NaN
573           6/20/2013      NaN
13                  NaN      NaN

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 6, 20), datetime.date(2013, 6, 28)}
Most recent date: 2013-06-28
names=['Wood St & Division St']
unique_names=['Wood St & Division St']
{'Name': ['Wood St & Division St'], 'Popularity': [7]}
                    Name  Popularity
0  Wood St & Division St           7
name='Wood St & Division St'
C=551    Chicago
13     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.903294875
longitude=-87.672880625

i=18
     ID                       Name   Latitude  Longitude  DP Capacity  \
514  18  Wacker Dr & Washington St  41.883272 -87.637313           19
14   18  Wacker Dr & Washington St  41.883132 -87.637321           19
534  18  Wacker Dr & Washington St  41.883272 -87.637313           19
534  18  Wacker Dr & Washington St  41.883272 -87.637313           19
476  18  Wacker Dr & Washington St  41.883272 -87.637313           19
14   18  Wacker Dr & Washington St  41.883272 -87.637313           19

     Landmark         Online Date     City
514       NaN  6/22/2013 19:00:47  Chicago
14        NaN     6/22/2013 19:00  Chicago

In [14]:
new_df

,ID,Name,Latitude,Longitude,City,DP Capacity,Landmark,Online Date
2,2,Buckingham Fountain,41.874615,-87.622639,Chicago,27,541.0,2015-05-08
3,3,Shedd Aquarium,41.867226,-87.615355,Chicago,31,544.0,2015-04-24
4,4,Burnham Harbor,41.856268,-87.613348,Chicago,23,545.0,2015-05-16
5,5,State St & Harrison St,41.874029,-87.627722,Chicago,19,30.0,2013-06-28
6,6,DuSable Harbor,41.885042,-87.612795,Chicago,39,548.0,2015-04-24
...,...,...,...,...,...,...,...,...
622,622,California Ave & Cortez St,41.900363,-87.696704,Chicago,15,None,2017-04-27
623,623,Michigan Ave & 8th St,41.872773,-87.623981,Chicago,23,None,2017-06-13
624,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,Chicago,16,None,2017-07-26
625,625,Chicago Ave & Dempster St,42.041691,-87.680687,Evanston,15,None,2017-08-11
626,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,Chicago,19,None,2017-12-21

In [15]:
new_df.to_csv(str(CLEAN_DIR / 'stations.csv'))

## Other Stations

Other station IDs were found in the CSV files describing all the bike trips.

In [ ]:
from_ids = unique_values("From Station ID")
to_ids = unique_values("To Station ID")

In [3]:
stations = pd.read_csv(CLEAN_DIR / 'stations.csv')