In [6]:
from cs1.tools import *

In [7]:
cd(DATA_DIR)

'/home/fuzzy/DataAnalysisLab/Case_Study_1/data'

In [8]:
TRIP_FILES = list_trip_files()

In [4]:
TRIP_FILES

[PosixPath('202108-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2018_Q4.csv'),
 PosixPath('202007-divvy-tripdata.csv'),
 PosixPath('202008-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2017_Q2.csv'),
 PosixPath('Divvy_Trips_2016_Q1.csv'),
 PosixPath('202005-divvy-tripdata.csv'),
 PosixPath('202010-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2014-Q3-0809.csv'),
 PosixPath('Divvy_Trips_2016_Q4.csv'),
 PosixPath('202110-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2014-Q4.csv'),
 PosixPath('202006-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2013.csv'),
 PosixPath('Divvy_Trips_2019_Q4.csv'),
 PosixPath('Divvy_Trips_2015_08.csv'),
 PosixPath('Divvy_Trips_2019_Q3.csv'),
 PosixPath('202109-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2015_07.csv'),
 PosixPath('202106-divvy-tripdata.csv'),
 PosixPath('202112-divvy-tripdata.csv'),
 PosixPath('202004-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2019_Q1.csv'),
 PosixPath('Divvy_Trips_2018_Q3.csv'),
 PosixPath('Divvy_Trips_2015-Q2.csv'),
 PosixPath('202107-divvy-tripdata.csv'),
 PosixPath('202105-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2016_05.csv'),
 PosixPath('Divvy_Trips_2018_Q2.csv'),
 PosixPath('202104-divvy-tripdata.csv'),
 PosixPath('202012-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2014_Q1Q2.csv'),
 PosixPath('Divvy_Trips_2019_Q2.csv'),
 PosixPath('Divvy_Trips_2018_Q1.csv'),
 PosixPath('202011-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2015_Q4.csv'),
 PosixPath('202009-divvy-tripdata.csv'),
 PosixPath('202103-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2016_06.csv'),
 PosixPath('Divvy_Trips_2016_04.csv'),
 PosixPath('202101-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2020_Q1.csv'),
 PosixPath('202201-divvy-tripdata.csv'),
 PosixPath('Divvy_Trips_2015-Q1.csv'),
 PosixPath('Divvy_Trips_2017_Q1.csv'),
 PosixPath('Divvy_Trips_2014-Q3-07.csv'),
 PosixPath('Divvy_Trips_2016_Q3.csv'),
 PosixPath('Divvy_Trips_2017_Q4.csv'),
 PosixPath('Divvy_Trips_2017_Q3.csv'),
 PosixPath('Divvy_Trips_2015_09.csv'),
 PosixPath('202102-divvy-tripdata.csv'),
 PosixPath('202111-divvy-tripdata.csv')]

In [9]:
sum_df = None
for i, p in enumerate(TRIP_FILES[1:]):
    df = pd.read_csv(p.name)
    print(f'Processing file {p.name}')
    print(f'{len(df[df["User Type"].isna()])=}')
    print(f'{len(df)=}')
    if not df["User Type"].isna().all():
        sum_df = pd.concat([sum_df, df.drop(df[df["User Type"].isna()])]) if not sum_df is None else df
sum_df if sum_df else "None"

Processing file Divvy_Trips_2018_Q4.csv
len(df[df["User Type"].isna()])=0
len(df)=642686
Processing file 202007-divvy-tripdata.csv
len(df[df["User Type"].isna()])=0
len(df)=551480

KeyError: "['ID', 'Bike ID', 'Start Time', 'End Time', 'From Station Name', 'From Station ID', 'To Station Name', 'To Station ID', 'Start Latitude', 'Start Longitude', 'End Latitude', 'End Longitude', 'User Type'] not found in axis"

In [9]:
df = pd.read_csv(TRIP_FILES[0])

In [10]:
len(df)

804352

In [7]:
len(df[df["User Type"].isna()])

0

In [14]:
df

,ID,Bike ID,Start Time,End Time,From Station Name,From Station ID,To Station Name,To Station ID,Start Latitude,Start Longitude,End Latitude,End Longitude,User Type
0,99103BB87CC6C1BB,electric_bike,2021-08-10 17:15:49,2021-08-10 17:22:44,NaN,NaN,NaN,NaN,41.770000,-87.680000,41.770000,-87.680000,M
1,EAFCCCFB0A3FC5A1,electric_bike,2021-08-10 17:23:14,2021-08-10 17:39:24,NaN,NaN,NaN,NaN,41.770000,-87.680000,41.770000,-87.630000,member
2,9EF4F46C57AD234D,electric_bike,2021-08-21 02:34:23,2021-08-21 02:50:36,NaN,NaN,NaN,NaN,41.950000,-87.650000,41.970000,-87.660000,member
3,5834D3208BFAF1DA,electric_bike,2021-08-21 06:52:55,2021-08-21 07:08:13,NaN,NaN,NaN,NaN,41.970000,-87.670000,41.950000,-87.650000,member
4,CD825CB87ED1D096,electric_bike,2021-08-19 11:55:29,2021-08-19 12:04:11,NaN,NaN,NaN,NaN,41.790000,-87.600000,41.770000,-87.620000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
804347,5E5C9CD681E0419C,classic_bike,2021-08-07 18:07:43,2021-08-07 18:21:21,Wells St & Evergreen Ave,TA1308000049,Lincoln Ave & Diversey Pkwy,TA1307000064,41.906724,-87.634830,41.932225,-87.658617,member
804348,96FB57CF4AA456F6,electric_bike,2021-08-09 08:49:31,2021-08-09 09:03:51,Broadway & Sheridan Rd,13323,Clark St & Lincoln Ave,13179,41.952709,-87.649940,41.915973,-87.634762,member
804349,226A0910DCCE904C,classic_bike,2021-08-12 16:55:57,2021-08-12 17:15:10,Dearborn St & Adams St,TA1305000005,Clark St & Lincoln Ave,13179,41.879356,-87.629791,41.915689,-87.634600,member
804350,1A97D27AE23DE1E7,classic_bike,2021-08-08 22:47:43,2021-08-08 23:08:12,Broadway & Sheridan Rd,13323,Clark St & Winnemac Ave,TA1309000035,41.952833,-87.649993,41.973348,-87.667855,casual
804351,BBC36E4AA3652361,electric_bike,2021-08-27 18:53:53,2021-08-27 19:02:16,Paulina Ave & North Ave,TA1305000037,Dayton St & North Ave,13058,41.909851,-87.669808,41.910674,-87.649547,casual

In [17]:
def unique_values(s):
    v = list()
    for f in list_trip_files():
        df = pd.read_csv(f)
        for u in df[s].dropna().unique():
            v.append(u)
    v = list(set(v))
    # v.sort()
    if '' in v:
        v = v.remove('')
    return v

In [18]:
unique_values("Bike ID")

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 'electric_bike',
 861,
 863,
 862,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1007,
 1008,
 1009,
 1010,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 ...]

In [13]:
for i, r in enumerate(df.loc):
    if i == 0:
        print("Data Frame location accessed successfully.")
        print(f'{len(r.index)=}')
        t = r["User Type"]
        print(f'{t=}')
        k = reverse_lookup(USER_VALS, t)
        print(f'{k=}')
        df.loc[0,"User Type"] = k
        print(f'{r["User Type"]=}')
    if i > 10:
        break
print(df.loc[0,"User Type"])

Data Frame location accessed successfully.
len(r.index)=13
t='member'
k='M'
r["User Type"]='member'
M

In [ ]:
for i in range(len(df)):
    r = df[i]
    if i == 0:
        print("Data Frame location accessed successfully.")
        print(f'{len(r.index)=}')
        t = r["User Type"]
        print(f'{t=}')
        k = reverse_lookup(USER_VALS, t)
        print(f'{k=}')
        r["User Type"] = k
        print(f'{r["User Type"]=}')

In [8]:
len(df.columns)

12

In [ ]:
for i in df.index:
    df.loc[i]["User Type"] = df.loc[i]["User Type"][0].upper()

In [19]:
list_trip_files()[0]

PosixPath('202108-divvy-tripdata.csv')